# Generated by Django 5.2.14 on 2026-05-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="current_section_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="branch_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tenant_id",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Current section (school) or batch (college) for this student.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_students",
                to="academics.batch",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organizations.tenant",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_custom_login_id_per_tenant",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_login_id__isnull", False)),
                fields=("tenant", "custom_login_id"),
                name="unique_custom_login_id_per_tenant",
            ),
        ),
    ]
