# Generated by Django 5.2.14 on 2026-05-25 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_studentprofile_current_section_id_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, help_text="Phone number or custom_login_id used in the attempt.", max_length=100
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ("was_successful", models.BooleanField(db_index=True, default=False)),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reason for failure: 'wrong_password', 'user_not_found', 'account_inactive', 'locked_out'.",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant scope for the login attempt.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_attempts",
                        to="organizations.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "db_table": "accounts_login_attempt",
                "indexes": [
                    models.Index(
                        fields=["identifier", "tenant", "was_successful", "created_at"],
                        name="accounts_lo_identif_a73bfa_idx",
                    )
                ],
            },
        ),
    ]
