# Generated by Django 5.2.15 on 2026-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_unique_email_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Platform Owner'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=20),
        ),
    ]
