# Generated by Django 5.2.15 on 2026-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0002_alter_tenant_institution_type_featureflag_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('email__isnull', False)), fields=('email',), name='unique_tenantless_email'),
        ),
    ]
