# Generated by Django 5.2.15 on 2026-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_unique_tenantless_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=15),
        ),
    ]
