# Generated by Django 5.2.14 on 2026-06-30 14:09

import apps.accounts.models.token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_studentguardianlink_notification_channels"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("otp_hash", models.CharField(max_length=256)),
                ("email_sent_to", models.EmailField(blank=True, default="", max_length=254)),
                ("expires_at", models.DateTimeField(default=apps.accounts.models.token.default_mfa_token_expiry)),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Token",
                "verbose_name_plural": "MFA Tokens",
                "db_table": "accounts_mfa_token",
                "indexes": [
                    models.Index(fields=["user", "is_used", "expires_at"], name="accounts_mf_user_id_f6da21_idx")
                ],
            },
        ),
    ]
