# Generated by Django 5.2.15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auth_audit_log_and_student_id_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingIdentityChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("phone", "Phone Number"), ("email", "Email Address")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        help_text="The new phone number or email address.",
                        max_length=200,
                    ),
                ),
                ("otp_hash", models.CharField(max_length=256)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_identity_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Identity Change",
                "verbose_name_plural": "Pending Identity Changes",
                "db_table": "accounts_pending_identity_change",
            },
        ),
        migrations.AddIndex(
            model_name="pendingidentitychange",
            index=models.Index(
                fields=["user", "change_type", "is_verified", "expires_at"],
                name="accounts_pe_user_id_change_idx",
            ),
        ),
    ]
