# Generated by Django 5.2.15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_pending_identity_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="family_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                db_index=True,
                help_text=(
                    "Shared by all rotations of one login session. "
                    "Re-use of any revoked family member revokes the entire family."
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="generation",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Increments on each rotation. Useful for debugging token chains.",
            ),
        ),
    ]
