# Generated by Django 5.2.14 on 2026-07-01 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_refresh_token_family"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pendingidentitychange",
            new_name="accounts_pe_user_id_9f7b58_idx",
            old_name="accounts_pe_user_id_change_idx",
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="family_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                help_text="Shared by all rotations of one login session. Re-use of any revoked family member revokes the entire family.",
            ),
        ),
    ]
