# Generated by Django 5.2.15 on 2026-07-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_accounts_pe_user_id_change_idx_accounts_pe_user_id_9f7b58_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkthroughCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_walkthrough_completion',
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_walkthrough_key_per_user')],
            },
        ),
    ]
