# Generated by Django 5.2.14 on 2026-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicperiod",
            name="name",
            field=models.CharField(help_text='e.g. "Term 1"', max_length=50),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(help_text='e.g. "2024-25"', max_length=20),
        ),
        migrations.AlterField(
            model_name="batch",
            name="name",
            field=models.CharField(help_text='e.g. "Section A"', max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="regulation",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_credits",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="credits",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_elective",
            field=models.BooleanField(default=False),
        ),
    ]
