# Generated by Django 5.2.15 on 2026-06-23 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_syllabusunit'),
        ('organizations', '0006_branch_working_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studymaterial',
            name='academics_s_branch__5e550b_idx',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='academics.timetableentry'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['branch', 'batch'], name='academics_s_branch__12c40b_idx'),
        ),
    ]
