# Generated by Django 5.2.14 on 2026-06-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_syllabusunitprogress"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studymaterialfolder",
            new_name="academics_s_branch__0811f2_idx",
            old_name="academics_s_branch__folder_idx",
        ),
        migrations.RenameIndex(
            model_name="syllabusunitprogress",
            new_name="academics_s_branch__a9e230_idx",
            old_name="academics_sy_branch__a8f3c1_idx",
        ),
    ]
