# Generated by Django 5.2.14 on 2026-07-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_adminreviewdismissal_holiday_half_day"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminreviewdismissal",
            new_name="academics_a_branch__c9889c_idx",
            old_name="academics_r_branch__rev_idx",
        ),
    ]
