# Generated by Django 5.2.14 on 2026-07-11 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_rename_academics_r_branch__rev_idx_academics_a_branch__c9889c_idx'),
        ('accounts', '0019_user_avatar_s3_key'),
        ('organizations', '0018_notification_center_mvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPromotionDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('student_name', models.CharField(max_length=255)),
                ('branch_id_snapshot', models.UUIDField(db_index=True)),
                ('course_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('course_name', models.CharField(blank=True, default='', max_length=120)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('section_name', models.CharField(blank=True, default='', max_length=50)),
                ('recommended_action', models.CharField(choices=[('promote', 'Promote'), ('retain', 'Retain'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdrawn', 'Withdrawn'), ('manual_review', 'Manual Review'), ('pending', 'Pending')], max_length=20)),
                ('recommended_reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('recommended_reason_label', models.CharField(blank=True, default='', max_length=255)),
                ('final_action', models.CharField(choices=[('promote', 'Promote'), ('retain', 'Retain'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdrawn', 'Withdrawn'), ('manual_review', 'Manual Review'), ('pending', 'Pending')], max_length=20)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_decisions', to='accounts.studentprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_promotion_decision',
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPromotionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], db_index=True, default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_sessions_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_sessions', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_sessions_from', to='academics.academicyear')),
                ('target_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_sessions_to', to='academics.academicyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_promotion_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPromotionOverrideLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('from_action', models.CharField(choices=[('promote', 'Promote'), ('retain', 'Retain'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdrawn', 'Withdrawn'), ('manual_review', 'Manual Review'), ('pending', 'Pending')], max_length=20)),
                ('to_action', models.CharField(choices=[('promote', 'Promote'), ('retain', 'Retain'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdrawn', 'Withdrawn'), ('manual_review', 'Manual Review'), ('pending', 'Pending')], max_length=20)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_override_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='academics.academicpromotiondecision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='academics.academicpromotionsession')),
            ],
            options={
                'db_table': 'academics_promotion_override_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='academics.academicpromotionsession'),
        ),
        migrations.AddConstraint(
            model_name='academicpromotionsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('branch', 'source_year'), name='unique_draft_promotion_per_branch_source'),
        ),
        migrations.AddConstraint(
            model_name='academicpromotionsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('branch', 'source_year'), name='unique_approved_promotion_per_branch_source'),
        ),
        migrations.AddConstraint(
            model_name='academicpromotiondecision',
            constraint=models.UniqueConstraint(fields=('session', 'student_profile'), name='unique_decision_per_student_session'),
        ),
    ]
