# Generated by Django 5.2.14 on 2026-07-11 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_promotion_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='block_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='execution_readiness',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('blocked', 'Blocked')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='target_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='target_course_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='target_course_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='target_fee_structure_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='target_fee_structure_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='academicpromotiondecision',
            name='target_section_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='execution_preview_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='lock_fingerprint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='preparation_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='preparation_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_sessions_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='preparation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='preparation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('locked', 'Locked'), ('invalid', 'Invalid')], db_index=True, default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='staleness_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='validation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AcademicPromotionPreparationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('event', models.CharField(choices=[('lock', 'Lock'), ('unlock', 'Unlock'), ('invalidated', 'Invalidated')], max_length=15)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_preparation_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_logs', to='academics.academicpromotionsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_promotion_preparation_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPromotionClassMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('source_course_id', models.UUIDField(db_index=True)),
                ('source_course_name', models.CharField(blank=True, default='', max_length=120)),
                ('target_course_id', models.UUIDField(db_index=True)),
                ('target_course_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_mappings', to='academics.academicpromotionsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_promotion_class_mapping',
                'constraints': [models.UniqueConstraint(fields=('session', 'source_course_id'), name='unique_class_mapping_per_session_source')],
            },
        ),
    ]
