# Generated by Django 5.2.15 on 2026-07-11 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_promotion_phase2_preparation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpromotionsession',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_sessions_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='execution_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='execution_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='academicpromotionsession',
            name='rollover_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_sessions', to='academics.academicrolloverrun'),
        ),
        migrations.AlterField(
            model_name='academicpromotionpreparationlog',
            name='event',
            field=models.CharField(choices=[('lock', 'Lock'), ('unlock', 'Unlock'), ('invalidated', 'Invalidated'), ('executed', 'Executed')], max_length=15),
        ),
        migrations.CreateModel(
            name='AcademicPromotionExecutionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('student_total', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('current_decision_id', models.UUIDField(blank=True, null=True)),
                ('current_student_name', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_duration_ms', models.PositiveIntegerField(default=0)),
                ('estimated_remaining_ms', models.PositiveIntegerField(default=0)),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('retained_count', models.PositiveIntegerField(default=0)),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('transferred_count', models.PositiveIntegerField(default=0)),
                ('withdrawn_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('fee_assignments_created', models.PositiveIntegerField(default=0)),
                ('opening_balances_carried', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_execution_runs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='academics.academicpromotionsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_promotion_execution_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPromotionExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('action', models.CharField(choices=[('promote', 'Promote'), ('retain', 'Retain'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdrawn', 'Withdrawn'), ('manual_review', 'Manual Review'), ('pending', 'Pending')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('prior_enrollment_id', models.UUIDField(blank=True, null=True)),
                ('new_enrollment_id', models.UUIDField(blank=True, null=True)),
                ('fee_assignment_id', models.UUIDField(blank=True, null=True)),
                ('opening_balance_paise', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='academics.academicpromotiondecision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='academics.academicpromotionexecutionrun')),
            ],
            options={
                'db_table': 'academics_promotion_execution_log',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('run', 'decision'), name='unique_execution_log_per_run_decision')],
            },
        ),
    ]
