# Generated by Django 5.2.15 on 2026-06-22 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('organizations', '0006_branch_working_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(choices=[('all', 'Everyone'), ('batch', 'Batch'), ('department', 'Department'), ('role', 'Role')], default='all', max_length=15)),
                ('target_value', models.CharField(blank=True, default='', max_length=100)),
                ('target_label', models.CharField(blank=True, default='', max_length=150)),
                ('scope', models.CharField(choices=[('institution', 'Institution'), ('branch', 'Branch')], default='branch', max_length=15)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communications_announcement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', '-created_at'], name='communicati_branch__23b9e9_idx')],
            },
        ),
    ]
