# Generated by Django 5.2.14 on 2026-07-11 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0005_remove_galleryphoto"),
        ("organizations", "0018_notification_center_mvp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("attendance", "Attendance"),
                            ("fees", "Fees"),
                            ("examination", "Examination"),
                            ("admissions", "Admissions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notification_type", models.CharField(db_column="type", max_length=64)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("critical", "Critical")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(max_length=512)),
                ("related_entity_type", models.CharField(blank=True, default="", max_length=64)),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("dedup_key", models.CharField(max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizations.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "communications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "-created_at"], name="communicati_recipie_fc8f0b_idx"),
                    models.Index(fields=["branch", "-created_at"], name="communicati_branch__2c6ec5_idx"),
                    models.Index(fields=["recipient", "read_at"], name="communicati_recipie_f632a7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "recipient", "dedup_key"), name="unique_notification_dedup_per_recipient"
                    )
                ],
            },
        ),
    ]
