# Generated by Django 5.2.14 on 2026-07-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_notification_center_mvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("attendance", "Attendance"),
                    ("fees", "Fees"),
                    ("examination", "Examination"),
                    ("admissions", "Admissions"),
                    ("academics", "Academics"),
                ],
                max_length=20,
            ),
        ),
    ]
