from .calendar import AcademicPeriod, AcademicYear, Holiday, HolidayType, PeriodType
from .rollover import AcademicRolloverRun, RolloverRunStatus
from .promotion import (
    AcademicPromotionClassMapping,
    AcademicPromotionDecision,
    AcademicPromotionExecutionLog,
    AcademicPromotionExecutionRun,
    AcademicPromotionOverrideLog,
    AcademicPromotionPreparationLog,
    AcademicPromotionSession,
    ExecutionLogStatus,
    ExecutionReadiness,
    PreparationLogEvent,
    PreparationStatus,
    PromotionAction,
    PromotionExecutionStatus,
    PromotionSessionStatus,
)
from .curriculum import BatchFaculty, BatchFacultyRole, BatchSubject, Subject, SubjectType
from .structure import Batch, Course, Department, DepartmentType
from .timetable import (
    DayOfWeek,
    PeriodSlot,
    Room,
    Timetable,
    TimetableEntry,
    TimetableEntryStatus,
)
from .admin_extras import (
    AcademicSubstitution,
    AdminReviewDismissal,
    CalendarChange,
    CalendarChangeType,
    StudyMaterial,
    StudyMaterialFolder,
    SubstitutionStatus,
    SyllabusUnit,
    SyllabusUnitProgress,
)

Grade = Course
Section = Batch

__all__ = [
    "AcademicYear",
    "AcademicPeriod",
    "PeriodType",
    "Holiday",
    "HolidayType",
    "Department",
    "DepartmentType",
    "Course",
    "Grade",
    "Batch",
    "Section",
    "Subject",
    "SubjectType",
    "BatchSubject",
    "BatchFaculty",
    "BatchFacultyRole",
    "PeriodSlot",
    "Room",
    "Timetable",
    "TimetableEntry",
    "DayOfWeek",
    "TimetableEntryStatus",
    "AcademicRolloverRun",
    "RolloverRunStatus",
    "AcademicPromotionSession",
    "AcademicPromotionDecision",
    "AcademicPromotionOverrideLog",
    "AcademicPromotionClassMapping",
    "AcademicPromotionPreparationLog",
    "AcademicPromotionExecutionRun",
    "AcademicPromotionExecutionLog",
    "PromotionAction",
    "PromotionSessionStatus",
    "PromotionExecutionStatus",
    "ExecutionLogStatus",
    "PreparationStatus",
    "ExecutionReadiness",
    "PreparationLogEvent",
    "AcademicSubstitution",
    "AdminReviewDismissal",
    "SubstitutionStatus",
    "StudyMaterial",
    "StudyMaterialFolder",
    "SyllabusUnit",
    "SyllabusUnitProgress",
    "CalendarChange",
    "CalendarChangeType",
]
