# Generated by Django 5.2.15 on 2026-06-12 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concession_requests', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='admissions.studentenrollment'),
        ),
    ]
