# Generated by Django 5.2.14 on 2026-07-10 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def publish_existing_structures(apps, schema_editor):
    FeeStructure = apps.get_model("fees", "FeeStructure")
    FeeStructure.objects.all().update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_alter_concessionrequest_student_and_more"),
        ("organizations", "0017_rename_organizatio_tenant__a1b2c3_idx_organizatio_tenant__a56c8a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="parent_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="fees.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_fee_structures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                db_index=True,
                default="draft",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="FeeHead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition"),
                            ("transport", "Transport"),
                            ("hostel", "Hostel"),
                            ("exam", "Exam"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=15,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[("mandatory", "Mandatory"), ("optional", "Optional")],
                        default="mandatory",
                        max_length=12,
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[("one_time", "One-time"), ("recurring", "Recurring")],
                        default="recurring",
                        max_length=12,
                    ),
                ),
                (
                    "refund_type",
                    models.CharField(
                        choices=[("refundable", "Refundable"), ("non_refundable", "Non-refundable")],
                        default="non_refundable",
                        max_length=16,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fee_heads", to="organizations.branch"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Head",
                "verbose_name_plural": "Fee Heads",
                "db_table": "fees_fee_head",
                "constraints": [
                    models.UniqueConstraint(fields=("branch", "name"), name="unique_fee_head_name_per_branch")
                ],
            },
        ),
        migrations.RunPython(publish_existing_structures, migrations.RunPython.noop),
    ]
