# Generated by Django 5.2.14 on 2026-07-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
        ("fees", "0004_student_concession_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentconcession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_concessions",
                to="admissions.studentenrollment",
            ),
        ),
    ]
