# Generated by Django 5.2.14 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0014_promotion_workspace"),
        ("fees", "0005_alter_studentconcession_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeinvoice",
            name="carry_forward_state",
            field=models.CharField(
                choices=[("normal", "Normal"), ("carried_forward", "Carried forward")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="carried_forward_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carried_from_invoices",
                to="fees.feeinvoice",
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="opening_balance_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("promotion", "Academic Year Promotion"),
                    ("rollover", "Academic Year Rollover"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="opening_balance_source_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_balance_invoices",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="promotion_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_balance_invoices",
                to="academics.academicpromotionsession",
            ),
        ),
    ]
