# Generated by Django 5.2.14 on 2026-07-09 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_rename_academics_s_branch__folder_idx_academics_s_branch__0811f2_idx_and_more"),
        ("gallery", "0002_migrate_legacy_gallery"),
        ("organizations", "0017_rename_organizatio_tenant__a1b2c3_idx_organizatio_tenant__a56c8a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="galleryalbum",
            new_name="gallery_alb_branch__17b786_idx",
            old_name="gallery_alb_branch_batch_slug",
        ),
        migrations.RenameIndex(
            model_name="galleryalbum",
            new_name="gallery_alb_branch__21865f_idx",
            old_name="gallery_alb_branch_created",
        ),
        migrations.RenameIndex(
            model_name="galleryimage",
            new_name="gallery_ima_album_i_91e3f2_idx",
            old_name="gallery_img_album_sort",
        ),
        migrations.RenameIndex(
            model_name="galleryimage",
            new_name="gallery_ima_album_i_67b4ad_idx",
            old_name="gallery_img_album_hash",
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL = school album; set = class album.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_albums",
                to="academics.batch",
            ),
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_list",
                to="organizations.branch",
            ),
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
