# Generated by Django 5.2.14 on 2026-07-28 16:29

import apps.gallery.models.album
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_galleryimage_stored_bytes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryalbum",
            name="visibility",
            field=models.JSONField(blank=True, default=apps.gallery.models.album._default_visibility),
        ),
    ]
