# Generated by Django 5.2.15 on 2026-06-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicrolloverrun'),
        ('attendance', '0001_initial'),
        ('organizations', '0003_branch_geofence_radius_m_branch_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_session_per_class_slot_day',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='batch',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode',
            field=models.CharField(choices=[('day', 'Day-wise (one mark per student per day)'), ('session', 'Session-wise (one mark per class period)')], default='session', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='batch_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.batchsubject'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='period_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.periodslot'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_subject__isnull', False)), fields=('batch_subject', 'date', 'period_slot'), name='unique_session_per_class_slot_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_subject__isnull', True)), fields=('batch', 'date'), name='unique_day_session_per_batch'),
        ),
    ]
