# Generated by Django 5.2.15 on 2026-06-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('attendance', '0002_remove_attendancesession_unique_session_per_class_slot_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='admissions.studentenrollment'),
        ),
    ]
