"""Interactors — exam seating generation."""

from django.db import transaction
from django.utils import timezone
from rest_framework.exceptions import ValidationError

from apps.academics.queries import timetable as tt_q
from apps.examinations.queries import exam as exam_q
from apps.examinations.queries import registration as reg_q
from apps.examinations.queries import seating as seat_q


def _seat_capacity(room, slot) -> int:
    if slot.max_capacity:
        return slot.max_capacity
    return room.capacity


def _build_seating_plan(slot, allocations, total_students, note: str) -> dict:
    return {
        "examSlotId": str(slot.pk),
        "generatedAt": timezone.now().isoformat(),
        "totalStudents": total_students,
        "allocations": allocations,
        "note": note,
    }


def _allocate_students_to_rooms(*, slot, rooms, students) -> tuple[list[dict], int]:
    sorted_students = sorted(students, key=lambda r: r.student.user.full_name.lower())
    idx = 0
    allocations = []

    for room in rooms:
        if idx >= len(sorted_students):
            break
        capacity = _seat_capacity(room, slot) if room.pk == slot.room_id else room.capacity
        take = min(capacity, len(sorted_students) - idx)
        seats = []
        for seat_no in range(1, take + 1):
            reg = sorted_students[idx + seat_no - 1]
            seats.append(
                {
                    "studentId": str(reg.student.student_profile_id),
                    "enrollmentId": str(reg.student_id),
                    "studentName": reg.student.user.full_name,
                    "seatNo": seat_no,
                }
            )
        allocations.append(
            {
                "roomId": str(room.pk),
                "roomName": room.name,
                "seats": seats,
            }
        )
        idx += take

    return allocations, len(sorted_students) - idx


@transaction.atomic
def generate_seating_for_slot(exam, slot, *, branch_id, room_ids=None, user=None) -> dict:
    """Generate seating for one schedule slot (EC-EXAM-05 partial last room)."""
    if slot.exam_id != exam.pk:
        raise ValidationError({"examSlotId": "Schedule slot does not belong to this exam."})

    rooms = []
    if room_ids:
        for room_id in room_ids:
            room = tt_q.get_room(branch_id, room_id)
            if not room:
                raise ValidationError({"roomIds": f"Room {room_id} not found in this branch."})
            rooms.append(room)
    else:
        room = tt_q.get_room(branch_id, slot.room_id)
        if not room:
            raise ValidationError({"roomId": "Schedule slot room not found."})
        rooms = [room]

    registrations = list(
        reg_q.list_registrations(exam.pk, batch_id=slot.batch_id)
    )
    if not registrations:
        raise ValidationError({"classSectionId": "No registered students for this batch."})

    seat_q.soft_delete_seatings_for_slot(slot.pk, user=user)

    allocations, remaining = _allocate_students_to_rooms(slot=slot, rooms=rooms, students=registrations)

    rows = []
    for allocation in allocations:
        room_id = allocation["roomId"]
        for seat in allocation["seats"]:
            rows.append(
                {
                    "schedule_slot_id": slot.pk,
                    "student_id": seat["enrollmentId"],
                    "room_id": room_id,
                    "seat_number": str(seat["seatNo"]),
                }
            )
    seat_q.bulk_create_seatings(rows, user=user)

    if remaining > 0:
        note = f"Not enough seats: {remaining} students unallocated. Add more rooms or increase capacity."
    elif len(rooms) > 1 and allocations and len(allocations[-1]["seats"]) < rooms[-1].capacity:
        note = "Auto-generated; last room partially filled (EC-EXAM-05)."
    else:
        note = "Auto-generated by filling rooms sequentially."

    return _build_seating_plan(slot, allocations, len(registrations), note)


@transaction.atomic
def generate_seating_for_exam(exam, *, branch_id, exam_slot_id=None, room_ids=None, user=None) -> list[dict]:
    if exam_slot_id:
        slot = exam_q.get_schedule_slot(exam.pk, exam_slot_id)
        if not slot:
            raise ValidationError({"examSlotId": "Schedule slot not found for this exam."})
        return [generate_seating_for_slot(exam, slot, branch_id=branch_id, room_ids=room_ids, user=user)]

    slots = list(exam_q.list_schedule_slots(exam.pk))
    if not slots:
        raise ValidationError({"examId": "No schedule slots to generate seating for."})
    return [
        generate_seating_for_slot(exam, slot, branch_id=branch_id, room_ids=room_ids, user=user)
        for slot in slots
    ]
