# Generated by Django 5.2.14 on 2026-07-11 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('organizations', '0019_tenantsettings_faculty_id_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_public_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(default='Admission Enquiry', max_length=150)),
                ('description', models.TextField(blank=True, default='Fill in your details and our team will get back to you.')),
                ('fields', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_form', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry Form',
                'verbose_name_plural': 'Enquiry Forms',
                'db_table': 'admissions_enquiry_form',
            },
        ),
    ]
