# Generated by Django 5.2.15 on 2026-08-02 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_promotion_phase3_execution'),
        ('admissions', '0003_unique_active_enrollment_per_student_year'),
        ('organizations', '0021_alter_licensepayment_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('mode', models.CharField(choices=[('create', 'Create new only'), ('update', 'Update existing only'), ('upsert', 'Create + update')], default='create', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('file_key', models.CharField(blank=True, default='', max_length=512)),
                ('error_report_key', models.CharField(blank=True, default='', max_length=512)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('row_payload', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_import_jobs', to='academics.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_import_jobs', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_import_jobs', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_student_import_job',
                'indexes': [models.Index(fields=['tenant', 'branch', 'status', 'created_at'], name='admissions__tenant__252c06_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentImportMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_import_mappings', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_import_mappings', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_import_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_student_import_mapping',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'branch', 'name'), name='unique_active_student_import_mapping_name')],
            },
        ),
    ]
