# Generated by Django 5.2.15 on 2026-06-11 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_academicrolloverrun"),
        ("accounts", "0009_studentprofile_academic_status"),
        ("fees", "0001_initial"),
        ("organizations", "0003_branch_geofence_radius_m_branch_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=10),
                ),
                (
                    "batch_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academics.batchsubject",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "faculty"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "examinations_assignment",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("file_key", models.CharField(blank=True, default="", max_length=512)),
                (
                    "plagiarism_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Similarity indicator only (F-126).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("graded_marks", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                (
                    "submission_status",
                    models.CharField(
                        choices=[("submitted", "Submitted"), ("late", "Late"), ("graded", "Graded")],
                        default="submitted",
                        max_length=15,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="examinations.assignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
                "db_table": "examinations_assignment_submission",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=150)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit Test"),
                            ("midterm", "Midterm"),
                            ("final", "Final"),
                            ("internal", "Internal"),
                            ("practical", "Practical"),
                            ("arrear", "Arrear"),
                        ],
                        default="internal",
                        max_length=15,
                    ),
                ),
                (
                    "exam_fee_paise",
                    models.BigIntegerField(
                        default=0, help_text="Flat exam fee charged on registration (Stage 3 fees integration)."
                    ),
                ),
                (
                    "marks_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Faculty marks submission deadline (EC-FORM-05).", null=True
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Denormalized convenience — true when results are published."
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[("provisional", "Provisional"), ("published", "Published"), ("revised", "Revised")],
                        default="provisional",
                        max_length=15,
                    ),
                ),
                (
                    "publish_in_progress",
                    models.BooleanField(
                        default=False,
                        help_text="Set during two-step publish to block concurrent publishers (EC-CONCUR-01).",
                    ),
                ),
                (
                    "academic_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exams", to="academics.academicperiod"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exams", to="organizations.branch"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "db_table": "examinations_exam",
            },
        ),
        migrations.CreateModel(
            name="ExamRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "fee_paid",
                    models.BooleanField(
                        default=False, help_text="Derived from fee_invoice.status == PAID; cached for hall-ticket gate."
                    ),
                ),
                (
                    "is_arrear",
                    models.BooleanField(default=False, help_text="College arrear registration (F-049/F-129)."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="examinations.exam",
                    ),
                ),
                (
                    "fee_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_registrations",
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_registrations",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Registration",
                "verbose_name_plural": "Exam Registrations",
                "db_table": "examinations_exam_registration",
            },
        ),
        migrations.CreateModel(
            name="ExamScheduleSlot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "max_capacity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Override room capacity for this slot; defaults to room.capacity.",
                        null=True,
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2, help_text="Snapshot from subject; overridable per slot.", max_digits=6
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_schedule_slots",
                        to="academics.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="examinations.exam",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_schedule_slots",
                        to="academics.room",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_schedule_slots",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Schedule Slot",
                "verbose_name_plural": "Exam Schedule Slots",
                "db_table": "examinations_exam_schedule_slot",
            },
        ),
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                ("bands", models.JSONField(default=list, help_text="[{min_percent, max_percent, grade, grade_point}]")),
                (
                    "grace_marks_max",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="College-only grace marks cap (F-050/F-128)."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Branch fallback when no course-specific scale exists."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_scales",
                        to="organizations.branch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="grade_scales", to="academics.course"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Scale",
                "verbose_name_plural": "Grade Scales",
                "db_table": "examinations_grade_scale",
            },
        ),
        migrations.CreateModel(
            name="HallTicket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("file_key", models.CharField(blank=True, default="", max_length=512)),
                ("roll_number", models.CharField(blank=True, default="", max_length=50)),
                (
                    "regulation",
                    models.CharField(
                        blank=True, default="", help_text="College regulation code; blank for school.", max_length=50
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_ticket",
                        to="examinations.examregistration",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hall Ticket",
                "verbose_name_plural": "Hall Tickets",
                "db_table": "examinations_hall_ticket",
            },
        ),
        migrations.CreateModel(
            name="InvigilatorDuty",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        limit_choices_to={"role": "faculty"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invigilator_duties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invigilator_duties",
                        to="examinations.examscheduleslot",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invigilator Duty",
                "verbose_name_plural": "Invigilator Duties",
                "db_table": "examinations_invigilator_duty",
            },
        ),
        migrations.CreateModel(
            name="MarksEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Null = absent (EC-EXAM-04).", max_digits=6, null=True
                    ),
                ),
                ("is_absent", models.BooleanField(default=False)),
                (
                    "is_internal",
                    models.BooleanField(default=False, help_text="Internal/continuous assessment marks vs exam marks."),
                ),
                (
                    "marks_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted"), ("locked", "Locked")],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "grace_applied",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="College-only grace marks applied (F-050).", max_digits=6
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks_entries",
                        to="examinations.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks_entries",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marks_entries",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marks Entry",
                "verbose_name_plural": "Marks Entries",
                "db_table": "examinations_marks_entry",
            },
        ),
        migrations.CreateModel(
            name="ResultPublication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("published_at", models.DateTimeField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("is_revised", models.BooleanField(default=False)),
                ("revision_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="False once superseded by a revision (EC-CONCUR-01 partial unique)."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="publications", to="examinations.exam"
                    ),
                ),
                (
                    "parent_publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="examinations.resultpublication",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_result_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Publication",
                "verbose_name_plural": "Result Publications",
                "db_table": "examinations_result_publication",
            },
        ),
        migrations.CreateModel(
            name="ResultRevisionHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("change_summary", models.TextField(blank=True, default="")),
                ("field_changes", models.JSONField(default=dict, help_text="Structured diff of changed fields.")),
                ("previous_snapshot_hash", models.CharField(blank=True, default="", max_length=64)),
                ("new_snapshot_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_result_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_history",
                        to="examinations.resultpublication",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Revision History",
                "verbose_name_plural": "Result Revision Histories",
                "db_table": "examinations_result_revision_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Seating",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("seat_number", models.CharField(max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="exam_seatings", to="academics.room"
                    ),
                ),
                (
                    "schedule_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seatings",
                        to="examinations.examscheduleslot",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_seatings",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seating",
                "verbose_name_plural": "Seatings",
                "db_table": "examinations_seating",
            },
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("total_marks", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("grade", models.CharField(blank=True, default="", max_length=10)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="College SGPA; null for school.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("is_pass", models.BooleanField(default=False)),
                (
                    "arrear_subjects",
                    models.JSONField(default=list, help_text="College arrear subject ids/names (F-049)."),
                ),
                ("report_card_key", models.CharField(blank=True, default="", max_length=512)),
                ("marksheet_key", models.CharField(blank=True, default="", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_results",
                        to="examinations.exam",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_results",
                        to="examinations.resultpublication",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Result",
                "verbose_name_plural": "Student Results",
                "db_table": "examinations_student_result",
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["branch", "batch_subject", "status"], name="examination_branch__9258a1_idx"),
        ),
        migrations.AddConstraint(
            model_name="assignmentsubmission",
            constraint=models.UniqueConstraint(
                fields=("assignment", "student"), name="unique_submission_per_assignment_student"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["branch", "academic_period", "exam_type"], name="examination_branch__598a00_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="examregistration",
            constraint=models.UniqueConstraint(fields=("exam", "student"), name="unique_registration_per_exam_student"),
        ),
        migrations.AddIndex(
            model_name="examscheduleslot",
            index=models.Index(fields=["room", "start_at", "end_at"], name="examination_room_id_b0150b_idx"),
        ),
        migrations.AddIndex(
            model_name="examscheduleslot",
            index=models.Index(fields=["exam", "batch"], name="examination_exam_id_41b5d7_idx"),
        ),
        migrations.AddConstraint(
            model_name="gradescale",
            constraint=models.UniqueConstraint(
                fields=("branch", "course", "name"), name="unique_grade_scale_name_per_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="invigilatorduty",
            constraint=models.UniqueConstraint(fields=("schedule_slot", "faculty"), name="unique_invigilator_per_slot"),
        ),
        migrations.AddIndex(
            model_name="marksentry",
            index=models.Index(fields=["exam", "subject", "marks_status"], name="examination_exam_id_65c8fd_idx"),
        ),
        migrations.AddConstraint(
            model_name="marksentry",
            constraint=models.UniqueConstraint(
                fields=("exam", "subject", "student"), name="unique_marks_per_exam_subject_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="resultpublication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)), fields=("exam",), name="unique_current_publication_per_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="seating",
            constraint=models.UniqueConstraint(
                fields=("schedule_slot", "room", "seat_number"), name="unique_seat_per_slot_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="seating",
            constraint=models.UniqueConstraint(
                fields=("schedule_slot", "student"), name="unique_student_per_schedule_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentresult",
            constraint=models.UniqueConstraint(fields=("exam", "student"), name="unique_result_per_exam_student"),
        ),
    ]
