# Generated by Django 5.2.15 on 2026-06-12 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('examinations', '0002_marks_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='marksentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='seating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seatings', to='admissions.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='admissions.studentenrollment'),
        ),
    ]
