# Generated by Django 5.2.15 on 2026-06-22 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_department_parent'),
        ('accounts', '0010_studentprofile_current_enrollment'),
        ('examinations', '0003_alter_assignmentsubmission_student_and_more'),
        ('organizations', '0006_branch_working_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text='Null = not yet entered / absent.', max_digits=6, null=True)),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('hard_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_internal_marks', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='academics.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examinations_internal_mark',
                'indexes': [models.Index(fields=['branch', 'subject'], name='examination_branch__764ae7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student_profile', 'subject'), name='unique_internal_mark_per_student_subject')],
            },
        ),
    ]
