# Generated by Django 5.2.14 on 2026-07-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportexport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("attendance_monthly", "Attendance — Monthly"),
                    ("fee_defaulters", "Fees — Defaulters"),
                    ("fee_collection", "Fees — Collection"),
                    ("admission_funnel", "Admissions — Funnel"),
                    ("hr_leave_summary", "HR — Leave Summary"),
                    ("naac", "NAAC / NIRF"),
                    ("fee_ledger", "Fees — Ledger"),
                    ("attendance_shortage", "Attendance — Shortage"),
                    ("attendance_ranking", "Attendance — Ranking"),
                    ("attendance_detention", "Attendance — Detention"),
                ],
                max_length=30,
            ),
        ),
    ]
