# Generated by Django 5.2.14 on 2026-07-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_extend_report_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportexport",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reportexport",
            name="format",
            field=models.CharField(default="csv", max_length=10),
        ),
    ]
