# Generated by Django 5.2.14 on 2026-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_add_self_service_report_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportexport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("attendance_monthly", "Attendance — Monthly"),
                    ("fee_defaulters", "Fees — Defaulters"),
                    ("fee_collection", "Fees — Collection"),
                    ("admission_funnel", "Admissions — Funnel"),
                    ("hr_leave_summary", "HR — Leave Summary"),
                    ("naac", "NAAC / NIRF"),
                    ("fee_ledger", "Fees — Ledger"),
                    ("attendance_shortage", "Attendance — Shortage"),
                    ("attendance_ranking", "Attendance — Ranking"),
                    ("attendance_detention", "Attendance — Detention"),
                    ("faculty_subject_attendance", "Faculty — My Subject Attendance"),
                    ("faculty_class_results", "Faculty — My Class Results"),
                    ("student_attendance", "Student — My Attendance"),
                    ("student_fee_statement", "Student — My Fee Statement"),
                    ("student_exam_results", "Student — My Exam Results"),
                    ("branch_summary", "Branches — Summary"),
                ],
                max_length=30,
            ),
        ),
    ]
