# Generated by Django 5.2.14 on 2026-07-10 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_alter_reportexport_report_type"),
        ("organizations", "0017_rename_organizatio_tenant__a1b2c3_idx_organizatio_tenant__a56c8a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reportexport",
            name="module",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="reportexport",
            name="title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="reportexport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("attendance_monthly", "Attendance — Monthly"),
                    ("fee_defaulters", "Fees — Defaulters"),
                    ("fee_collection", "Fees — Collection"),
                    ("admission_funnel", "Admissions — Funnel"),
                    ("hr_leave_summary", "HR — Leave Summary"),
                    ("hr_headcount", "HR — Headcount"),
                    ("naac", "NAAC / NIRF"),
                    ("fee_ledger", "Fees — Ledger"),
                    ("attendance_shortage", "Attendance — Shortage"),
                    ("attendance_ranking", "Attendance — Ranking"),
                    ("attendance_detention", "Attendance — Detention"),
                    ("faculty_subject_attendance", "Faculty — My Subject Attendance"),
                    ("faculty_class_results", "Faculty — My Class Results"),
                    ("student_attendance", "Student — My Attendance"),
                    ("student_fee_statement", "Student — My Fee Statement"),
                    ("student_exam_results", "Student — My Exam Results"),
                    ("branch_summary", "Branches — Summary"),
                    ("exam_seating", "Examinations — Seating Plan"),
                    ("exam_class_results", "Examinations — Class Results"),
                    ("college_naac", "College — NAAC Export"),
                    ("college_nirf", "College — NIRF Export"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SavedReportFilter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("attendance_monthly", "Attendance — Monthly"),
                            ("fee_defaulters", "Fees — Defaulters"),
                            ("fee_collection", "Fees — Collection"),
                            ("admission_funnel", "Admissions — Funnel"),
                            ("hr_leave_summary", "HR — Leave Summary"),
                            ("hr_headcount", "HR — Headcount"),
                            ("naac", "NAAC / NIRF"),
                            ("fee_ledger", "Fees — Ledger"),
                            ("attendance_shortage", "Attendance — Shortage"),
                            ("attendance_ranking", "Attendance — Ranking"),
                            ("attendance_detention", "Attendance — Detention"),
                            ("faculty_subject_attendance", "Faculty — My Subject Attendance"),
                            ("faculty_class_results", "Faculty — My Class Results"),
                            ("student_attendance", "Student — My Attendance"),
                            ("student_fee_statement", "Student — My Fee Statement"),
                            ("student_exam_results", "Student — My Exam Results"),
                            ("branch_summary", "Branches — Summary"),
                            ("exam_seating", "Examinations — Seating Plan"),
                            ("exam_class_results", "Examinations — Class Results"),
                            ("college_naac", "College — NAAC Export"),
                            ("college_nirf", "College — NIRF Export"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_report_filters",
                        to="organizations.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_report_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_saved_report_filter",
                "indexes": [
                    models.Index(fields=["tenant", "user", "report_type"], name="analytics_s_tenant__331b80_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user", "report_type", "name"),
                        name="unique_saved_filter_name_per_user_report",
                    )
                ],
            },
        ),
    ]
