# Generated by Django 5.2.14 on 2026-05-24 19:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                (
                    "subdomain",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Subdomain must be lowercase alphanumeric with hyphens (e.g. greenfield-academy).",
                                regex="^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$",
                            )
                        ],
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[("school", "School"), ("college", "College")], default="school", max_length=10
                    ),
                ),
                ("logo_s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("address_line1", models.CharField(blank=True, default="", max_length=255)),
                ("address_line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deactivated", "Deactivated"),
                            ("offboarding", "Offboarding"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("parent_access_enabled", models.BooleanField(default=True)),
                ("mfa_enforced", models.BooleanField(default=False)),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "organizations_tenant",
            },
        ),
        migrations.CreateModel(
            name="PlanSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "plan",
                    models.CharField(
                        choices=[("starter", "Starter"), ("growth", "Growth"), ("enterprise", "Enterprise")],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "billing_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("student_limit", models.PositiveIntegerField(default=200)),
                ("storage_limit_gb", models.PositiveIntegerField(default=10)),
                ("sms_quota_per_month", models.PositiveIntegerField(default=500)),
                ("ai_token_quota_per_month", models.PositiveIntegerField(default=10000)),
                ("api_rpm_limit", models.PositiveIntegerField(default=100)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Subscription",
                "verbose_name_plural": "Plan Subscriptions",
                "db_table": "organizations_plan_subscription",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "student_id_label",
                    models.CharField(
                        default="Roll Number",
                        help_text='Label shown on login page for student ID. e.g. "Roll Number", "Admission Number".',
                        max_length=50,
                    ),
                ),
                (
                    "faculty_id_label",
                    models.CharField(
                        default="Employee ID",
                        help_text='Label shown on login page for faculty ID. e.g. "Employee ID", "Staff Code".',
                        max_length=50,
                    ),
                ),
                (
                    "attendance_threshold_percent",
                    models.PositiveSmallIntegerField(
                        default=75, help_text="Minimum attendance % required. Default: 75%."
                    ),
                ),
                ("exam_day_counts_toward_attendance", models.BooleanField(default=True)),
                ("grace_marks_enabled", models.BooleanField(default=False)),
                ("absent_exam_affects_gpa", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_settings",
                        to="organizations.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
                "db_table": "organizations_tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", help_text="Short code for reports (e.g. MC, NC).", max_length=20
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="True for the default campus created at tenant onboarding."
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "academic_year_start_month",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Month (1-12) when the academic year starts. Default: April.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="organizations.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "organizations_branch",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("code__gt", "")),
                        fields=("tenant", "code"),
                        name="unique_branch_code_per_tenant",
                    )
                ],
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
