# Generated by Django 5.2.15 on 2026-06-08 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College')], default='school', help_text='Immutable after the first academic-year rollover.', max_length=10),
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('key', models.SlugField(help_text="Stable identifier, e.g. 'ai_question_paper'. Unique per tenant (and once globally).", max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_percent', models.PositiveSmallIntegerField(default=100, help_text='0–100. Percentage of users the flag is on for when enabled.')),
                ('allowlist_user_ids', models.JSONField(blank=True, default=list, help_text='Explicit user UUIDs always included, regardless of rollout_percent.')),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null = global flag applying to every tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'organizations_feature_flag',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='unique_feature_flag_key_per_tenant'), models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('key',), name='unique_global_feature_flag_key')],
            },
        ),
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('resource', models.CharField(choices=[('students', 'Students'), ('storage_bytes', 'Storage (bytes)'), ('sms_count', 'SMS count'), ('ai_tokens', 'AI tokens'), ('api_calls', 'API calls')], db_index=True, max_length=20)),
                ('period', models.CharField(choices=[('month', 'Per month'), ('total', 'Lifetime total')], default='month', max_length=10)),
                ('period_start', models.DateField(help_text="First day of the window (or a sentinel for 'total').")),
                ('usage', models.BigIntegerField(default=0)),
                ('soft_cap', models.BigIntegerField(default=0, help_text='0 = no soft cap.')),
                ('hard_cap', models.BigIntegerField(default=0, help_text='0 = no hard cap.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Quota',
                'verbose_name_plural': 'Tenant Quotas',
                'db_table': 'organizations_tenant_quota',
                'indexes': [models.Index(fields=['tenant', 'resource', 'period_start'], name='organizatio_tenant__b5e5e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'resource', 'period_start'), name='unique_quota_per_tenant_resource_period')],
            },
        ),
    ]
