# Generated by Django 5.2.15 on 2026-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_tenant_institution_type_featureflag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Allowed radius in metres; null = geo-fence disabled.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='attendance_mode',
            field=models.CharField(choices=[('day', 'Day-wise (one mark per student per day)'), ('session', 'Session-wise (one mark per class period)')], default='session', max_length=10),
        ),
    ]
