# Generated by Django 5.2.15 on 2026-06-21 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branch_geofence_radius_m_branch_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a #RRGGBB hex value (e.g. #2563EB).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo_s3_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a #RRGGBB hex value (e.g. #2563EB).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(blank=True, default='#0EA5E9', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a #RRGGBB hex value (e.g. #2563EB).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(blank=True, default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a #RRGGBB hex value (e.g. #2563EB).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
    ]
