# Generated by Django 5.2.15 on 2026-06-21 18:10

import django.core.validators
from django.db import migrations, models


def clear_placeholder_blue(apps, schema_editor):
    """The first branding migration backfilled existing tenants with the old blue
    placeholder default. Clear those so they fall back to the green brand default."""
    Tenant = apps.get_model("organizations", "Tenant")
    Tenant.objects.filter(primary_color="#2563EB").update(primary_color="")
    Tenant.objects.filter(accent_color="#0EA5E9").update(accent_color="")


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_branch_accent_color_branch_logo_s3_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a #RRGGBB hex value (e.g. #2563EB).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a #RRGGBB hex value (e.g. #2563EB).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.RunPython(clear_placeholder_blue, migrations.RunPython.noop),
    ]
