# Generated by Django 5.2.15 on 2026-06-21 19:03

import apps.organizations.models.branch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_tenant_accent_color_alter_tenant_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='working_days',
            field=models.JSONField(blank=True, default=apps.organizations.models.branch.default_working_days),
        ),
    ]
