# Generated by Django 5.2.14 on 2026-07-04 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_platform_ops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('invoice_type', models.CharField(choices=[('initial', 'Initial'), ('top_up', 'Top-up'), ('renewal', 'Renewal')], default='top_up', max_length=10)),
                ('licenses_count', models.PositiveIntegerField()),
                ('unit_price_inr', models.PositiveIntegerField(default=499)),
                ('amount_inr', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='issued', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_invoices', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_license_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('licenses_granted', models.PositiveIntegerField()),
                ('amount_inr', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('bank_transfer', 'Bank transfer'), ('online', 'Online')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='organizations.licenseinvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_payments', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_license_payment',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('event_type', models.CharField(choices=[('student_enrolled', 'Student enrolled'), ('license_assigned', 'License assigned'), ('payment_received', 'Payment received'), ('invoice_generated', 'Invoice generated'), ('student_withdrawn', 'Student withdrawn'), ('student_restored', 'Student restored'), ('student_deleted', 'Student deleted'), ('student_transferred', 'Student transferred'), ('duplicate_merged', 'Duplicate merged'), ('subscription_renewed', 'Subscription renewed'), ('period_extended', 'Period extended'), ('manual_override', 'Manual override')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_events', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organizations.licensepayment')),
            ],
            options={
                'db_table': 'organizations_license_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantLicensePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('price_per_student_inr', models.PositiveIntegerField(default=499)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_pricing', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_tenant_license_pricing',
            },
        ),
        migrations.CreateModel(
            name='TenantSubscriptionPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('price_per_student_inr', models.PositiveIntegerField(default=499)),
                ('grace_ends_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_periods', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_tenant_subscription_period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantLicenseSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('licenses_purchased', models.PositiveIntegerField(default=0)),
                ('licenses_consumed', models.PositiveIntegerField(default=0)),
                ('unlicensed_active_count', models.PositiveIntegerField(default=0)),
                ('pending_amount_inr', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_summary', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('current_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.tenantsubscriptionperiod')),
            ],
            options={
                'db_table': 'organizations_tenant_license_summary',
            },
        ),
        migrations.CreateModel(
            name='StudentLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('student_name', models.CharField(blank=True, default='', max_length=255)),
                ('enrolled_at', models.DateTimeField(db_index=True)),
                ('license_status', models.CharField(choices=[('unlicensed', 'Unlicensed'), ('licensed', 'Licensed')], db_index=True, default='unlicensed', max_length=15)),
                ('licensed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_licenses', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('license_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licensed_students', to='organizations.licensepayment')),
                ('student_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_license', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_licenses', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('subscription_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_licenses', to='organizations.tenantsubscriptionperiod')),
            ],
            options={
                'db_table': 'organizations_student_license',
            },
        ),
        migrations.AddField(
            model_name='licenseinvoice',
            name='subscription_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='organizations.tenantsubscriptionperiod'),
        ),
        migrations.AddIndex(
            model_name='licensepayment',
            index=models.Index(fields=['tenant', 'paid_at'], name='organizatio_tenant__a0fce7_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseevent',
            index=models.Index(fields=['tenant', 'event_type'], name='organizatio_tenant__1e2ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscriptionperiod',
            index=models.Index(fields=['tenant', 'status'], name='organizatio_tenant__14e488_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscriptionperiod',
            index=models.Index(fields=['end_date', 'status'], name='organizatio_end_dat_edf9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlicense',
            index=models.Index(fields=['tenant', 'license_status', 'enrolled_at'], name='organizatio_tenant__39ca03_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlicense',
            index=models.Index(fields=['branch', 'license_status'], name='organizatio_branch__9e6d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseinvoice',
            index=models.Index(fields=['tenant', 'status'], name='organizatio_tenant__22ab82_idx'),
        ),
    ]
