# Generated by Django 5.2.14 on 2026-07-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_backfill_student_licenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditlog',
            name='category',
            field=models.CharField(choices=[('support', 'Support'), ('plan', 'Plan'), ('tenant', 'Tenant'), ('ticket', 'Ticket'), ('announcement', 'Announcement'), ('settings', 'Settings'), ('billing', 'Billing'), ('licensing', 'Licensing')], db_index=True, max_length=20),
        ),
    ]
