# Generated by Django 5.2.14 on 2026-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_platformauditlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseevent',
            name='event_type',
            field=models.CharField(choices=[('student_enrolled', 'Student enrolled'), ('license_assigned', 'License assigned'), ('payment_received', 'Payment received'), ('invoice_generated', 'Invoice generated'), ('student_withdrawn', 'Student withdrawn'), ('student_restored', 'Student restored'), ('student_deleted', 'Student deleted'), ('student_transferred', 'Student transferred'), ('duplicate_merged', 'Duplicate merged'), ('subscription_renewed', 'Subscription renewed'), ('subscription_grace', 'Subscription in grace'), ('subscription_expired', 'Subscription expired'), ('period_extended', 'Period extended'), ('manual_override', 'Manual override')], db_index=True, max_length=30),
        ),
    ]
