# Generated by Django 5.2.14 on 2026-07-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_licenseevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensepayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_payments', to='organizations.branch'),
        ),
    ]
