# Generated by Django 5.2.14 on 2026-07-09 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_materialized_billing_totals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentaicreditbalance",
            new_name="organizatio_tenant__a56c8a_idx",
            old_name="organizatio_tenant__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="studentaicredittxn",
            new_name="organizatio_tenant__49d036_idx",
            old_name="organizatio_tenant__d4e5f6_idx",
        ),
        migrations.AddField(
            model_name="studentaicreditbalance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentaicreditbalance",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="studentaicreditbalance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentaicreditbalance",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentaicredittxn",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="studentaicredittxn",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentaicredittxn",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="studentaicreditbalance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studentaicredittxn",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
