# Generated by Django 5.2.14 on 2026-07-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_rename_organizatio_tenant__a1b2c3_idx_organizatio_tenant__a56c8a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="fee_reminder_days",
            field=models.JSONField(
                blank=True, default=list, help_text="Days before due date to send fee reminders, e.g. [7, 5, 3, 1]."
            ),
        ),
    ]
