# Generated by Django 5.2.14 on 2026-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_notification_center_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='faculty_id_format',
            field=models.CharField(default='{BRANCH}-FAC-{SEQ}', help_text='Template for faculty employee IDs. Tokens: {BRANCH} {YEAR} {YY} {ROLE} {SEQ}.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='faculty_id_seq_width',
            field=models.PositiveSmallIntegerField(default=4, help_text='Zero-padding width for the {SEQ} token in faculty IDs.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='student_id_format',
            field=models.CharField(default='{BRANCH}/{YEAR}/{SEQ}', help_text='Template for student admission/roll IDs. Tokens: {BRANCH} {YEAR} {YY} {ROLE} {SEQ}.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='student_id_reset_yearly',
            field=models.BooleanField(default=True, help_text='Reset the student sequence each academic year (vs. run continuously).'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='student_id_seq_width',
            field=models.PositiveSmallIntegerField(default=5, help_text='Zero-padding width for the {SEQ} token in student IDs.'),
        ),
    ]
